postgres:
  user: "admin"
  pass: "guest"
  db: "sampledb"

expenseService:
  replicaCount: 1
  image: "quay.io/mkfsext4/ocpdev-deployments-review:4.12"
  host: "TODO"
  domain: "api.crc.testing:6443"
